# common
spring:
  profiles:
    active: local

--- ## local
spring:
  config:
    activate:
      on-profile: local

--- ## dev
spring:
  config:
    activate:
      on-profile: dev

--- ## prod
spring:
  config:
    activate:
      on-profile: prod