# common
spring:
  profiles:
    active: local
  config:
    import:
      - "classpath:config/db.yaml" # https://github.com/dev-sian/pyeon-schelin/pull/10 참고

--- ## local
spring:
  config:
    activate:
      on-profile: local

--- ## dev
spring:
  config:
    activate:
      on-profile: dev

--- ## prod
spring:
  config:
    activate:
      on-profile: prod
