# common
spring:
  profiles:
    active: local
  config:
    import:
      - "classpath:config/db.yaml"

--- ## local
spring:
  config:
    activate:
      on-profile: local

--- ## dev
spring:
  config:
    activate:
      on-profile: dev

--- ## prod
spring:
  config:
    activate:
      on-profile: prod