### get general post list
GET http://localhost:8080/posts/2?offset=1

### get review post list
GET http://localhost:8080/posts/1

### get general post
GET http://localhost:8080/post/2

### get review post
GET http://localhost:8080/post/3

### create general post
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title" : "insert General Post title",
  "content" : "insert General Post content",
  "boardId" : 2,
  "postType" : "GENERAL_POST",
  "writerId" : 1
}

### create review post
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title" : "insert Review Post title",
  "content" : "insert Review Post content",
  "boardId" : 1,
  "postType" : "REVIEW_POST",
  "writerId" : 1,
  "productName" : "로제불닭볶음면",
  "csName" : "GS25"
}

### update general post
PATCH http://localhost:8080/posts/9
Content-Type: application/json

{
  "title" : "update General Post title",
  "content" : "update General Post content",
  "boardId" : 2,
  "postType" : "GENERAL_POST"
}

### update review post
PATCH http://localhost:8080/posts/12
Content-Type: application/json

{
  "title" : "update Review Post title2",
  "boardId" : 1,
  "postType" : "REVIEW_POST",
  "productName" : "불닭볶"
}

### delete post
DELETE http://localhost:8080/posts/5