### user logout
GET http://localhost:8080/v1.0/users/logout

### select all
GET http://localhost:8080/v1.0/users

### user login
POST http://localhost:8080/v1.0/users/login
Content-Type: application/json

{
  "userId": "user25",
  "password": "1234"
}

### user create
POST http://localhost:8080/v1.0/users
Content-Type: application/json

{
  "userId": "user25",
  "name": "김영빈",
  "password": "1234"
}

### user test
GET http://localhost:8080/v1.0/user/test


